version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src/
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
     - MYSQL_DATABASE=goflight
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root